// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH3806sPlKAk4iaGT0hdrD41d1VsaXwGQ',
    appId: '1:827474499309:web:6333d95ea3e665b5c09ee4',
    messagingSenderId: '827474499309',
    projectId: 'buzz-with-aggie',
    authDomain: 'buzz-with-aggie.firebaseapp.com',
    databaseURL: 'https://buzz-with-aggie-default-rtdb.firebaseio.com',
    storageBucket: 'buzz-with-aggie.appspot.com',
    measurementId: 'G-3CMWNH2Q9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKiYPrSOhn2N3e91KReSPf0lvQGbmTCRk',
    appId: '1:827474499309:android:26d03aa621a7f6c6c09ee4',
    messagingSenderId: '827474499309',
    projectId: 'buzz-with-aggie',
    databaseURL: 'https://buzz-with-aggie-default-rtdb.firebaseio.com',
    storageBucket: 'buzz-with-aggie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1laczuM3sKGmZiOR_5En7Jl0oagwKbN8',
    appId: '1:827474499309:ios:37e10885acab89d0c09ee4',
    messagingSenderId: '827474499309',
    projectId: 'buzz-with-aggie',
    databaseURL: 'https://buzz-with-aggie-default-rtdb.firebaseio.com',
    storageBucket: 'buzz-with-aggie.appspot.com',
    iosClientId: '827474499309-2ea2cupsc3b5u3icq7g2kvfqrcrkm1o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzingBoothBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1laczuM3sKGmZiOR_5En7Jl0oagwKbN8',
    appId: '1:827474499309:ios:5f0b820435329db2c09ee4',
    messagingSenderId: '827474499309',
    projectId: 'buzz-with-aggie',
    databaseURL: 'https://buzz-with-aggie-default-rtdb.firebaseio.com',
    storageBucket: 'buzz-with-aggie.appspot.com',
    iosClientId: '827474499309-t9h1th6apv0sji329oqu12scrqo7nrp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzingBoothBlog.RunnerTests',
  );
}
